### ISSUE TITLE
Setup failed when switching from old helper version.

### ISSUE THREAD

**Issue by nom4dv3** [DelphinusLab/zkWasm-service-helper#33]
## issue statement
In previous versions, the `image_md5` used in sign message is `image_md5.toUpperCase()`, while in the current version, it changes to `image_md5.toLowerCase()`, causing errors.

And the error also looks confused:
```
error: { code: 401, message: 'Invalid data received' }
```

## reproduce
let info = {
  name: name,
  image_md5: image_md5.toUpperCase(), // This is enforced in previous versions, causing wrong sign msg in this version.
  image: image,
  user_address: user_address.toLowerCase(),
  description_url: description_url,
  avator_url: iconURL,
  circuit_size: circuitSize,
};

let msg = ZkWasmUtil.createAddImageSignMessage(info);
let signature = await signMessage(msg, user_privatekey);

then follow the recommended implementation in README.

## solution
probably need to make a note on this change, considering it's hard to make it compatible.

**Comment by nom4dv3** [comment]
New related issue: when querying tasks with md5, it requires toUpperCase, contradict to the sign message!
This is very confusing...
e.g.: 
- good query: https://rpc.zkwasmhub.com:8090/tasks?md5=E9C448C3E0788674B8B76CC65E387D1E
- bad query: https://rpc.zkwasmhub.com:8090/tasks?md5=e9c448c3e0788674b8b76cc65e387d1e

**Comment by nom4dv3** [comment]
New issue..... 
so the md5 of the Prove sign message requires toUpperCase(), toLowerCase() can't pass the verification...
can we unify it? otherwise very confusing...

**Comment by yymone** [comment]
Thanks for your raising issue.
Yes, we are fixing it.

We plan to unify it to case insensitive, so regardless the md5 is uppercase or lowercase, it can get correct result.
By theory the md5 is just a 32 hexadecimal digits, so uppercase or lowercase of letters are same.

Will update this issue when we fix it.
