### ISSUE TITLE
Mismatched signature derived

### ISSUE THREAD

**Issue by tohacking** [DelphinusLab/zkWasm-service-helper#78]
```
    let info: AddImageParams = {
        name: filename,
        image_md5: md5,
        image: fileSelected,
        user_address: cloudCredential.USER_ADDRESS.toLowerCase(),
        description_url: "Lg4",
        avator_url: "",
        circuit_size: 22,
        auto_submit_network_ids: [],
        prove_payment_src: ProvePaymentSrc.Default,
    };
```

 behaves different from:

```
    let info: AddImageParams = {
        name: filename,
        image_md5: md5,
        image: fileSelected,
        description_url: "Lg4",
        avator_url: "",
        circuit_size: 22,
        auto_submit_network_ids: [],
        user_address: cloudCredential.USER_ADDRESS.toLowerCase(),
        prove_payment_src: ProvePaymentSrc.Default,
    };
```

Notice the order of the variables changed. 

Receives error when using the latter when adding to the cloud prover.
{
  success: false,
  error: {
    code: 401,
    message: 'Mismatched signature derived: 0xf604…3909, given: 0xd8f1…6bde'
  }
}

**Comment by qozymandias** [comment]
Hi @tohacking 

The order of the attributes of `AddImageParams` is strict, as we need to sign and verify them. Please follow our [example.](https://github.com/DelphinusLab/zkWasm-service-helper/blob/78e35d85b4f3607cd2e762336d0547533fdf8065/examples/src/tasks/addNewImage.ts#L21)

In the future, we will provide a function for generating the struct, so users don't need to worry about the order of attributes.
